### ISSUE TITLE
[suggestion] automountbypass

### ISSUE THREAD

**Issue by 31173-commit** [C10udburst/meteor-rejects#16] opened 2021-06-17 07:12 UTC
add automountbypass so we don't have to put another jar in mods folder, and maybe bookdupe too

**Comment by C10udburst** [comment] 2021-06-17 11:10
Frankly, I don't see a reason why this should be implemented. Both of those addons have their respective repositories that are actively maintained. 

But as you may or may not have noticed this addon does contain modules taken from other meteor addons. This is done because those addons aren't actively maintained and aren't up to date with the current version of meteor.

The only benefit of putting automountbypass in this addon is the ability to put it in the "Rejects" category, but it is filled with modules as is, so it doesn't really seem that useful.

Also duplicate of #14

**Closed by C10udburst** 2021-06-17 11:11 UTC

**Comment by 31173-commit** [comment] 2021-06-24 12:05
> Frankly, I don't see a reason why this should be implemented. Both of those addons have their respective repositories that are actively maintained.
> 
> But as you may or may not have noticed this addon does contain modules taken from other meteor addons. This is done because those addons aren't actively maintained and aren't up to date with the current version of meteor.
> 
> The only benefit of putting automountbypass in this addon is the ability to put it in the "Rejects" category, but it is filled with modules as is, so it doesn't really seem that useful.
> 
> Also duplicate of #14

then what about a thing like multiconnect

**Comment by C10udburst** [comment] 2021-07-18 12:40
> then what about a thing like multiconnect

what about multiconnect? what does it have to do with my point?
