### ISSUE TITLE
[Bug] Crashes on launch 

### ISSUE THREAD

**Issue by AlexKari** [C10udburst/meteor-rejects#26] opened 2021-07-28 23:06 UTC
Crash report [here](https://pastebin.com/y9upy8w0)

My mod folder has meteor 1.4.5, sodium 1.17, fabric-api, and this mod

It also doesn't work without sodium or fabric api

I haven't tried it with 1.17 yet, does this not work with 1.17.1?

**Comment by C10udburst** [comment] 2021-07-29 06:05
This looks very similar to the crash fixed by pr #1.

> I haven't tried it with 1.17 yet, does this not work with 1.17.1?

In theory this mod should work with 1.17.1 and the newest devbuild of meteor

**Comment by C10udburst** [comment] 2021-07-29 08:35
@AlexKari I can't reproduce this crash. Does this happen with only meteor installed?

**Comment by C10udburst** [comment] 2021-07-29 08:40
Nevermind i figured it out. You've downloaded a wrong file. [THIS IS THE CORRECT ONE](https://github.com/C10udburst/meteor-rejects/releases/download/latest-1.17/meteor-rejects-addon-0.0.4.jar). Dont use the `*-dev.jar` files

**Closed** 2021-07-29 08:41 UTC
Labels: bug, can't reproduce, invalid
